version: "{build}"

branches:
  except:
    - /^travis.*$/

clone_depth: 10

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIGURATION: MinSizeRel
      TOOLSET: v141_xp
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIGURATION: Release
      TOOLSET: v141_xp
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
build_script:
  - md build
  - cd build
  - cmake -G "%GENERATOR%" -T "%TOOLSET%" ..
  - cmake --build . --config "%CONFIGURATION%" -- /verbosity:minimal

after_build:
  - set OUTPUT_DIR=%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\
  - 7z a ..\CompiledWindows.zip "%OUTPUT_DIR%*.exe" "%OUTPUT_DIR%*.pk3" "%OUTPUT_DIR%*.dll"

artifacts:
  - path: CompiledWindows.zip

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
