language: c++
dist: trusty

branches:
  except:
    - /^appveyor.*$/

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7"

    - os: linux
      compiler: gcc
      env:
        - GCC_VERSION=4.9
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Wno-maybe-uninitialized"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libsdl2-dev
            - libgtk2.0-dev

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - $CC --version
  - $CXX --version

script:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - >
    cmake ${CMAKE_OPTIONS}       \
      -DFORCE_INTERNAL_ZLIB=YES  \
      -DFORCE_INTERNAL_JPEG=YES  \
      -DFORCE_INTERNAL_BZIP2=YES \
      -DFORCE_INTERNAL_GME=YES   \
      -DPK3_QUIET_ZIPDIR=YES     \
      ..
  - make -j2 -k

notifications:
  email: false

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $githubtoken # Set in travis-ci.org dashboard
#  on:
#    branch: master

deploy:
  provider: releases
  api_key: $githubreleasetoken # Set in travis-ci.org dashboard
  file_glob: true
  file: TRAVIS_BUILD_DIR/*
  skip_cleanup: true
  on:
    tags: true
