#define ZCC_EQ                              1
#define ZCC_MULEQ                           2
#define ZCC_DIVEQ                           3
#define ZCC_MODEQ                           4
#define ZCC_ADDEQ                           5
#define ZCC_SUBEQ                           6
#define ZCC_LSHEQ                           7
#define ZCC_RSHEQ                           8
#define ZCC_ANDEQ                           9
#define ZCC_OREQ                           10
#define ZCC_XOREQ                          11
#define ZCC_QUESTION                       12
#define ZCC_COLON                          13
#define ZCC_OROR                           14
#define ZCC_ANDAND                         15
#define ZCC_EQEQ                           16
#define ZCC_NEQ                            17
#define ZCC_APPROXEQ                       18
#define ZCC_LT                             19
#define ZCC_GT                             20
#define ZCC_LTEQ                           21
#define ZCC_GTEQ                           22
#define ZCC_LTGTEQ                         23
#define ZCC_IS                             24
#define ZCC_DOTDOT                         25
#define ZCC_OR                             26
#define ZCC_XOR                            27
#define ZCC_AND                            28
#define ZCC_LSH                            29
#define ZCC_RSH                            30
#define ZCC_SUB                            31
#define ZCC_ADD                            32
#define ZCC_MUL                            33
#define ZCC_DIV                            34
#define ZCC_MOD                            35
#define ZCC_CROSSPROD                      36
#define ZCC_DOTPROD                        37
#define ZCC_POW                            38
#define ZCC_UNARY                          39
#define ZCC_ADDADD                         40
#define ZCC_SUBSUB                         41
#define ZCC_DOT                            42
#define ZCC_LPAREN                         43
#define ZCC_LBRACKET                       44
#define ZCC_SCOPE                          45
#define ZCC_EOF                            46
#define ZCC_SEMICOLON                      47
#define ZCC_COMMA                          48
#define ZCC_CLASS                          49
#define ZCC_IDENTIFIER                     50
#define ZCC_ABSTRACT                       51
#define ZCC_NATIVE                         52
#define ZCC_REPLACES                       53
#define ZCC_LBRACE                         54
#define ZCC_RBRACE                         55
#define ZCC_STRUCT                         56
#define ZCC_CONST                          57
#define ZCC_ENUM                           58
#define ZCC_STATES                         59
#define ZCC_NWS                            60
#define ZCC_STOP                           61
#define ZCC_WAIT                           62
#define ZCC_FAIL                           63
#define ZCC_LOOP                           64
#define ZCC_GOTO                           65
#define ZCC_PLUS                           66
#define ZCC_BRIGHT                         67
#define ZCC_FAST                           68
#define ZCC_SLOW                           69
#define ZCC_NODELAY                        70
#define ZCC_CANRAISE                       71
#define ZCC_OFFSET                         72
#define ZCC_RPAREN                         73
#define ZCC_LIGHT                          74
#define ZCC_STRCONST                       75
#define ZCC_DEFAULT                        76
#define ZCC_SBYTE                          77
#define ZCC_BYTE                           78
#define ZCC_SHORT                          79
#define ZCC_USHORT                         80
#define ZCC_INT                            81
#define ZCC_UINT                           82
#define ZCC_BOOL                           83
#define ZCC_FLOAT                          84
#define ZCC_DOUBLE                         85
#define ZCC_STRING                         86
#define ZCC_VECTOR                         87
#define ZCC_NAME                           88
#define ZCC_INTCONST                       89
#define ZCC_UINTCONST                      90
#define ZCC_MAP                            91
#define ZCC_ARRAY                          92
#define ZCC_VOID                           93
#define ZCC_RBRACKET                       94
#define ZCC_STATIC                         95
#define ZCC_PRIVATE                        96
#define ZCC_PROTECTED                      97
#define ZCC_LATENT                         98
#define ZCC_FINAL                          99
#define ZCC_META                           100
#define ZCC_ACTION                         101
#define ZCC_READONLY                       102
#define ZCC_DEPRECATED                     103
#define ZCC_IN                             104
#define ZCC_OUT                            105
#define ZCC_OPTIONAL                       106
#define ZCC_SUPER                          107
#define ZCC_SELF                           108
#define ZCC_TILDE                          109
#define ZCC_BANG                           110
#define ZCC_SIZEOF                         111
#define ZCC_ALIGNOF                        112
#define ZCC_FLOATCONST                     113
#define ZCC_NAMECONST                      114
#define ZCC_FALSE                          115
#define ZCC_TRUE                           116
#define ZCC_CONTINUE                       117
#define ZCC_BREAK                          118
#define ZCC_RETURN                         119
#define ZCC_DO                             120
#define ZCC_FOR                            121
#define ZCC_WHILE                          122
#define ZCC_UNTIL                          123
#define ZCC_IF                             124
#define ZCC_ELSE                           125
#define ZCC_SWITCH                         126
#define ZCC_CASE                           127
